### ISSUE TITLE
Error when using `yarn start`, refmt3.exe not found.

### ISSUE THREAD

**Issue by reinvanimschoot** [Schmavery/reprocessing#102]
I'm getting a strange error when cloning the project but replacing 

`"bs-platform": "bsansouci/bsb-native#2.1.1"` to either

`"bs-platform": "bsansouci/bsb-native#3.2.0"` OR `"bs-platform": "bsansouci/bsb-native`.

The error is get is the following:

![screen shot 2018-06-27 at 18 48 57](https://user-images.githubusercontent.com/35171567/42023925-577013fe-7ac1-11e8-88ac-1b158aab2c89.png)

I tried several times, cloning a fresh project, removing the global bs-platform but nothing works.

**Comment by Schmavery** [comment]
For now, you can try replacing the dependency on reprocessing with the #multifile-hotreloading branch. As soon as we can make sure that 3.2.0 is stable on all platforms we'll merge that branch to master :)

**Comment by Schmavery** [comment]
Actually @bsansouci just told me he just added refmt3 to the osx bundle as a workaround for now. Reinstalling bsb-native should fix it.

**Comment by bsansouci** [comment]
Does this work now?

**Comment by Schmavery** [comment]
I'll close this for now, but happy to reopen if you have more problems with this, so just give us a shout if you do!
