### ISSUE TITLE
Adding Example

### ISSUE THREAD

**Issue by sscaff1** [Schmavery/reprocessing#112]
Hi @Schmavery - Thank you for the great library. It's really great. Would you accept a PR for another example in the README. I made the mandelbrot set using Reprocessing (< 65 lines which is awesome).  Here is the repo (it contains a gif of the result). Here it is https://github.com/sscaff1/remandelbrot. Again thanks for the great library!

**Comment by Schmavery** [comment]
definitely! Please submit one 😄

**Comment by Schmavery** [comment]
Thanks again for submitting this, I love seeing what people are making :)
