### ISSUE TITLE
The module or file Reprocessing can't be found.

### ISSUE THREAD

**Issue by TyLer5S** [Schmavery/reprocessing#122]
I'm fairly new to to the ReasonML ecosystem, I try to and a `Js.log()` statement in my game for debugging purpose (to log out the state, complex structure, print_endline won't do it), but I got `The module or file Reprocessing can't be found.` error in my console when I `npm start`. How do I include Js module into my reprocessing project?

**Comment by Schmavery** [comment]
Are you able to build and run the example project? https://github.com/bsansouci/reprocessing-example

Hard to know what's going wrong without seeing your setup, maybe you're missing reprocessing in your bsconfig: https://github.com/bsansouci/reprocessing-example/blob/master/bsconfig.json#L4

**Comment by TyLer5S** [comment]
@Schmavery Hi Avery, thank you for looking into this, I can run the example project just fine, what I'm trying to do is to use something from the Js module, here's my code:
```reason
/* seeding to ensure to get random int every time, ref: https://til.hashrocket.com/posts/5mebc3fnbx-seeding-and-generating-random-integers-in-reasonml */
Random.init(int_of_float(Js.Date.now()));
Random.int(10);
```

When I run `npm start`, I got this:

```
  The module or file Js.Date can't be found.
  - If it's a third-party dependency:
    - Did you list it in bsconfig.json?
    - Did you run `bsb` instead of `bsb -make-world`
      (latter builds third-parties)?
  - Did you include the file's directory in bsconfig.json?
```

**Comment by TyLer5S** [comment]
@Schmavery Hi Avery, thank you so much for helping me understand why Js module is not available in the native environment, and also pointing me to the unix module!
