### ISSUE TITLE
Adding Support for WebGL / 3D Drawing Functions

### ISSUE THREAD

**Issue by hydrosquall** [Schmavery/reprocessing#124]
Hi team, thanks for the great work on this graphical means to practice with ReasonML!

I was wondering about whether the [3d drawing methods](https://github.com/processing/p5.js/wiki/Getting-started-with-WebGL-in-p5) in the p5.js port of processing (such as box, ortho, etc) are in the roadmap for Reprocessing.

To invoke these methods in p5.js, we would call in the setup function `createCanvas(width, height, sketch.WEBGL)`. Since `createCanvas` is part of the internal API in reprocessing instead of the public API, I was curious if you had any advice about how to go about doing 3d drawing with reprocessing, or if I should stick to regular p5.js to do that type of project.

For context, I am trying to get into reprocessing by porting an example from an [Observable Notebook](https://beta.observablehq.com/@hydrosquall/breathing-cube-in-p5-js) to Reprocessing.

Thanks for your time and consideration :)!

**Comment by Schmavery** [comment]
Hi @hydrosquall, thanks for checking us out. Right now, the short answer is that 3D isn't really on the roadmap, cause it would mean introducing quite a few new concepts (basic shapes as you mentioned, textures/materials along with lighting.. gets complicated!). We'd also need to figure out how best to extend the additional functions to optionally support a third dimension, or create a second "3D version" of several functions.

My original goal was to make something extremely easy to use and build real (2d) games and experiences with in ReasonML. I think Processing's 2D API does a great job at making graphics approachable. It would be really neat to be able to extend this to 3D creations but I do tend to feel that the 3D API is significantly more complex in some ways. It doesn't let you avoid the matrix functions which can be counterintuitive and camera logic gets more involved.

I've been looking into familiarizing myself a bit more with the 3D side of things lately so we'll see where that goes but no promises for the short term!

**Comment by Schmavery** [comment]
Added it to the FAQ! https://github.com/Schmavery/reprocessing/blob/master/README.md#why-is-there-no-support-for-3d-drawing

Thanks again :)
