### ISSUE TITLE
`Module not found` JS bundling error 

### ISSUE THREAD

**Issue by outkine** [Schmavery/reprocessing#125]
I'm trying to bundle a game for the web. The require_polyfill works great, but I haven't been able to get any JS bundlers to work because `bsb` generates some weird require statements:

#### `"package-specs": ["commonjs"]`
```javascript
var Reprocessing_Env = require("Reprocessing//home/anton/code/game/crazy-rideshare/node_modules/reprocessing/lib/js/src/Reprocessing_Env.js");
``` 
None of the bundlers I tried have been able to recognize this format.

#### `"package-specs": ["es6-global"]`
```javascript
import * as Reprocessing_Env from "../../../../../../../../node_modules/reprocessing/lib/home/anton/code/game/crazy-rideshare/node_modules/reprocessing/lib/es6_global/src/Reprocessing_Env.js";
```
This path is just plain wrong.

Is there a setting I'm missing that will generate correct import statements? [This](https://github.com/outkine/crazy-carsharing) is the project repo.

**Comment by bsansouci** [comment]
Hey thanks for reporting this issue. Which version of bsb-native are you using? 
I believe this should be fixed in 4.0.7000

**Comment by outkine** [comment]
I was using 4.0.6. I can confirm that 4.0.7000 fixes the problem, thank you so much for helping!

**Comment by bsansouci** [comment]
Great!

**Comment by Schmavery** [comment]
Don't forget to add a link to the game to the readme :)

**Comment by outkine** [comment]
For sure, as soon as it's presentable!
