### ISSUE TITLE
Is there a way to set the window title?

### ISSUE THREAD

**Issue by jozanza** [Schmavery/reprocessing#127]
I've been exploring the docs and the source code for this lib as well as the reasongl library, and I'm at a loss for how to set the window title. Is this supported?

**Comment by Schmavery** [comment]
Embarrassingly enough, I think there might not be a way. I'll see if I can do something about that, sorry...

https://github.com/bsansouci/reasongl/blob/118e254bec0de1210a62176cf8520ab842cf6377/src/native/reasongl_native.re#L27

**Comment by jozanza** [comment]
No problem! I ran into that same code block and thought, "There must be some other way to do this. I must have missed something". haha

Keep me posted 👍

**Comment by Schmavery** [comment]
I think I originally didn't do this because I wasn't sure what should happen on web. Do you think it's fine if it just updates document.title?

**Comment by jozanza** [comment]
Yeah that seems fine.

**Comment by Schmavery** [comment]
Thanks for the suggestion, it should be usable now so let me know if it has any issues :)

**Comment by jozanza** [comment]
@Schmavery are you going to publish a new version to npm?

**Comment by Schmavery** [comment]
fair enough

**Comment by jozanza** [comment]
<img width="400" alt="screen shot 2019-01-19 at 3 40 07 pm" src="https://user-images.githubusercontent.com/740794/51432126-952f6600-1c00-11e9-8eb8-b99936282150.png">
