### ISSUE TITLE
Labeled functions

### ISSUE THREAD

**Issue by IwanKaramazow** [Schmavery/reprocessing#20]
Does it make sense to expose labeled functions as the public API?
I really like the ergonomics of labeled args for this kind of UI programming
```reason
let rectf x y width height env => /* ... */

let rectf ::x ::y ::width ::height env => /* ... */
```

**Comment by Schmavery** [comment]
Yeah for sure, we've been discussing this already actually, just haven't done an api cleanup yet.
We started off this way to match the processing api as closely as possible, but I don't know any real reason why we couldn't have labelled args.

**Comment by Schmavery** [comment]
The latest refactor adds labelled args.  Thanks for the feedback (and sorry for the response time)!
