### ISSUE TITLE
feature: line cap support

### ISSUE THREAD

**Issue by jaredly** [Schmavery/reprocessing#25]
would love to have some rounded line caps on these

![image](https://user-images.githubusercontent.com/112170/27318463-b02ecda8-5549-11e7-97fd-8438431c6421.png)

**Comment by Schmavery** [comment]
Right, we're missing [strokeCap](https://processing.org/reference/strokeCap_.html) from reprocessing.  Can probably get away with drawing an ellipse on the end of every line for now.  I'll try to add an option for that soon.

**Comment by Schmavery** [comment]
Just implemented this:
![image](https://user-images.githubusercontent.com/2154522/27598242-be0064de-5b19-11e7-8cf4-a9e6296bfae8.png)
