### ISSUE TITLE
Cleanup API

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/reprocessing#27]
- [x] Expose everything from one module Reprocessing.  This should help with files conflicting with those in the local project scope. General proposed structure:
> - Reprocessing
>   - run function
>   - Env (alternate names: Draw, P)
>     - Contains functions that require env.  Usually these draw, but not always. (ex: rect, line, mousePressed)
>   - Utils
>     - Contains (mostly) stateless utility functions that don't require env. (ex: lerp, dist, noise)
>   - Constants
>     - Contains constants exposed by processing. (ex: pi, white, black)

Alternately, Utils and Env could be merged if that's more intuitive.  I'd love to keep Utils separate (and stateless), but I'm tending towards merging them, especially since there might be a bit of a discoverability problem here, where it can be hard for users to know what will require env while they're looking for a particular function. No idea what to call the merged module.  We could even just shove them all into the Reprocessing namespace, though then opening that module puts a loooot of stuff into the namespace (and it puts it right next to `run`, which is fairly different from the other functions).  In this case, it would probably be best for people to just alias Reprocessing to something small and explicitly qualify all accesses to the internal functions.  

- [x] Labelled arguments #20 
- [x] Add docs
- [x] Remove builtin OCaml functions from Utils when they are named the same in OCaml.   Open to suggestion here. (ex: max, min, sqrt, sin)

**Comment by Schmavery** [comment]
Curious to know if there are opinions about this redesign from people who have already tried the current api a little. @IwanKaramazow @jaredly @bsansouci

**Comment by jaredly** [comment]
Overall I love the idea!

I think I'd like `Reprocessing.Draw` to have all drawing functions, and have a separate namespace for getters like `mousePressed`, maybe called `Env`?

**Comment by Schmavery** [comment]
Sounds reasonable.  Do things like `stroke` and `fill` live in Draw because they have to do with drawing, or Env because they don't actually draw?  I'm guessing the former.

**Comment by Schmavery** [comment]
Other edge cases: rotate, translate, loadImage/Font, size, push/popStyle.
If I had to guess, I'd probably say all in Draw except for size...

**Comment by jaredly** [comment]
the former. Basically what I'm thinking is "anything that maps to something on the HTML5 Canvas Context object would be in draw"

**Comment by Schmavery** [comment]
Tracking my progress in #29.  Feel free to chime in, anyone who has an opinion.

**Comment by Schmavery** [comment]
This is merged now.
