### ISSUE TITLE
Create pretty docs

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/reprocessing#30]
There are a lot of ocaml docs generators...
Unfortunately no one has put one on npm yet.
Options to experiment with:

- Can ocamldoc maybe be exposed by the reason-cli?  If so, this might be the easiest option.
- odoc -- doesn't seem to have much documentation.
- codoc -- more documentation.. less widely used?  Really hard to tell.
- https://github.com/smondet/oredoc -- a bit of a wildcard, but looks very simple... Either port to npm or use as a pattern to implement out own...
- ???

**Comment by Schmavery** [comment]
I've been hearing things about bsdoc.. fingers crossed.

**Comment by jaredly** [comment]
I've been itching to make a docs generator, might jump into this in the near future

**Comment by Schmavery** [comment]
Would be great, then we could stop pointing people to processing docs haha

**Comment by Schmavery** [comment]
We've currently given up on generating docs (😢) and we're working on a docusaurus site to help with this issue.

**Comment by Schmavery** [comment]
Initial version published :) Opened https://github.com/Schmavery/reprocessing/issues/85 to follow up on improvements
