### ISSUE TITLE
Strokes don't transform properly

### ISSUE THREAD

**Issue by ryanartecona** [Schmavery/reprocessing#34]
Given this example program:

```reason
open Reprocessing;

let setup env => {
  Env.size width::600 height::400 env;
  ()
};

let draw () env => {
  let (width, height) = (Env.width env, Env.height env);
  Draw.background Constants.black env;
  Draw.stroke Constants.red env;
  Draw.fill Constants.blue env;
  Draw.translate x::150. y::150. env;
  Draw.rotate (Constants.pi /. 60.) env;
  Draw.rect pos::((-100), (-100)) width::200 height::200 env;
  ()
};

run ::setup ::draw ();
```

I get this output (in the browser, so using reason-web):
![image](https://user-images.githubusercontent.com/889991/28949367-f3ab2b3e-7881-11e7-953b-d2bdf4cdf1a0.png)

It looks to me like the current transform is getting applied once for the fill and twice for the stroke? The center of the red stroke is twice as far away from the top left origin than the blue fill, and it's also rotated more.

Possibly related, if I don't have a stroke at all (e.g. comment out the `Draw.stroke` line from the above example), the corners of a rect fill get clipped awkwardly:

![image](https://user-images.githubusercontent.com/889991/28949430-6d8a33c8-7882-11e7-821f-c03a91321593.png)

Not sure if this is intentional or not, but it's at least unexpected for me as a newcomer. I can make the clipping go away by setting the stroke width to 0, but if there is no stroke color by default, why does my fill get clipped?

**Comment by ryanartecona** [comment]
I might have time to look into this later myself if someone can point me in the right direction.

**Comment by Schmavery** [comment]
Ran out of time to fix this tonight but it should be pretty straightforward, looks like I'm applying the transformation twice on the stroke like you said.

For the second, you need to explicitly set `Draw.noStroke env;` to remove the stroke.  Seems like the second image is displaying with a black-colored stroke by default.  I was actually just thinking I should make the default noStroke, which might be more intuitive.

Thanks for reporting these issues! It also really helped to have the images explaining.

**Comment by Schmavery** [comment]
I made noStroke the default and fixed this transform bug.  Lmk how it goes.

**Comment by ryanartecona** [comment]
Thanks! Just verified this is working perfectly for me now.
