### ISSUE TITLE
Add helpers for handling intersection logic

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/reprocessing#42]
One common problem I (and @bsansouci) have run into issues with detecting intersections/collisions between simple shapes.

Even rect/rect collision has enough little edge cases that implementing it usually takes me a couple tries to get right.  Maybe this is just me, lmk if you don't think this is complex enough to warrant helper code.

I was considering adding one or two `Utils` functions that will implement detection of intersections between simple shapes (ellipses, rects).
```reason
let intersectRectRect ::pos1 ::w1 ::h1 ::pos2 ::w2 ::h2;
let intersectRectEllipse ::pos1 ::w1 ::h1 ::center2 ::radX2 ::radY2;
let intersectEllipseEllipse ::center1 ::radX1 ::radY1 ::center2 ::radX2 ::radY2;
```
There are 2 problems that I see here.
1) Each function has many arguments. This is made slightly easier to reason about by named args.
2) This can combinatorially blow up with the number of types of things you want to test intersection for.

This led me to a second idea:
```reason
type shapeT = 
| Rect {x: float, y: float, w: float, h: float}
| Ellipse {x: float, y: float, radx: float, rady: float};

let intersect (s1 : shapeT) (s2 : shapeT);
```
This has the advantage of only needing one function to do any type of intersection, but the disadvantage of needing to allocate 2 records/variants every time you want to test intersection. I'm not sure if this is enough overhead to matter, really.

One thing I'm not sure it's useful to note is that the shapes that are being intersected will frequently (in my experience) be the same as some shapes that are being drawn.  I'm not sure how often this is actually the case though, as many slightly more involved demos/games will probably use sprites/images rather than rect while still checking intersection using rects.

I'm not sure if idea 1 or idea 2 are better, they seem to have tradeoffs. Thoughts?

**Comment by bsansouci** [comment]
To add to this, you'd render with one function instead of many:
```
let render {x, y} => {
  let rect = Rect {x, y, width: 100, height: 100};
  draw rect;
  {x, y}
};
```

**Comment by Schmavery** [comment]
@bsansouci that's a possibility as well, yeah..
I alluded to it in my second-to-last paragraph but I'm still trying to decide if it's worth it.
The set of things you'd want to intersect is similar to but not necessarily the same as the set of things you'd want to draw.  Images for instance don't have a very clearly defined intersection behaviour (presumably it would be the same as rectangles).

I'm currently kind of inclined to go for the first (simple? direct?) option as a prototype and iterate to the second if it becomes cumbersome.

**Comment by Schmavery** [comment]
Added some very simple ones in 26b805315aa14dd5d885debac8c58e8c9a7d37d7
Will reopen later if they need to be revisited.
