### ISSUE TITLE
The arc implementation is janky

### ISSUE THREAD

**Issue by jaredly** [Schmavery/reprocessing#52]
<img width="121" alt="image" src="https://user-images.githubusercontent.com/112170/33460314-d50459fa-d5ea-11e7-98de-b9891af67844.png">

^ in the middle is supposed to be 4 even quarters of a pie, w/ no space between them. Also the pink ring is done w/ `ellipse` -- there's not supposed to be a gap.

<img width="76" alt="image" src="https://user-images.githubusercontent.com/112170/33460390-2f801cc0-d5eb-11e7-8a43-1add826bca9d.png">

and this is supposed to be two halves of a pie.

<img width="57" alt="image" src="https://user-images.githubusercontent.com/112170/33460427-457489a8-d5eb-11e7-890c-173bc4450884.png">

also see the overlap ^ where the dot on the right is brighter. This is an ellipse that's semitransparent.

cc @bsansouci

**Comment by Schmavery** [comment]
Mhh, seems like it might be an off-by-one issue. Can you post the code snippets so that I can make sure I understand what's happening?
Not surprised there are a couple artifacts with alpha, that was added after most of the other code. Will try to clean it up.

**Comment by jaredly** [comment]
It's not an off-by-one, it's the fact that the arcs have a limit on the granularity that they render. It's because we're doing like a 30-sided polygon, and if the length of the arc wants to be 29.5 of those sides, we only render 29 sides.

**Comment by jaredly** [comment]
Here's an example of animating an arc, and you can see how jerky it is
https://schmavery.github.io/reprocessing/?gist=69fb9c2733776faab624d45046c1bfa7

**Comment by Schmavery** [comment]
Right, I was hoping it wouldn't be that haha. Thanks for double checking. Might need some fancy logic to handle the ends of the arc properly.

**Comment by jaredly** [comment]
although actually maybe there is an off-by-one in there too, see https://schmavery.github.io/reprocessing/?gist=3e929c7dc5392e2cbc8d17aa1cff4f3d

**Comment by Schmavery** [comment]
This is a good reminder for me to fix the gist capability in the web env..

**Comment by Schmavery** [comment]
Hopefully 54be1fc4dd4d9a8a5753d765b8b4124ab8dcf45b fixes this?

**Comment by Schmavery** [comment]
Will close these arc issues. Please lmk if they don't help and we can reopen them. Thanks!
