### ISSUE TITLE
Arc rendering is broken when scaled

### ISSUE THREAD

**Issue by jaredly** [Schmavery/reprocessing#55]
```
Draw.scale(~x=1.2, ~y=1.2, env);
/* do an arc */
```

The circle is in the right place, but the one of the arcs drawn is quite sad. Also the 4 dots in the upper left are not supposed to be there.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/112170/33522685-a9f5f20c-d7af-11e7-894e-b369498045a6.png">

**Comment by Schmavery** [comment]
Oh no! Will see what I can do.

**Comment by Schmavery** [comment]
Hopefully a01dc4a77d9f9c7851e28db751b759b013e346d4 fixes this?
