### ISSUE TITLE
Can't run bytecode or native

### ISSUE THREAD

**Issue by boyswan** [Schmavery/reprocessing#56]
`❯ ./lib/bs/bytecode/indexhot.byte

dyld: Library not loaded: /Users/Jack/Desktop/regl/node_modules/sdl2/libSDL2-2.0.0.dylib
  Referenced from: /Users/Jack/Desktop/reprocessing-example/./lib/bs/bytecode/indexhot.byte
  Reason: image not found
[1]    79641 abort      ./lib/bs/bytecode/indexhot.byte`

same error for byte and native, not sure why it's pointing to a regl directory?

**Comment by bsansouci** [comment]
Could you give us a bit of context as to what you did to install and build?

This looks to me like you installed stuff in a folder called `regl` and then moved the `node_modules` into another project.

**Comment by boyswan** [comment]
cloned the react-example project and tried both yarn and npm (v4) install. Seemed to be working a week or so ago, updated to High Sierra OSX so wondering if that has something to do with it. The regl directory is very odd, it doesn't even exist

**Comment by bsansouci** [comment]
That's... super strange. Have you tried nuking `node_modules` and `yarn.lock` and re-installing?

**Comment by Schmavery** [comment]
Yeah this is super weird, we definitely want to make sure we can get this working for you asap.
Just to cover our bases, I'm assuming your install would have gone like this: 
```
git clone https://github.com/bsansouci/reprocessing-example.git
npm install
npm run build
npm start
```

Assuming @bsansouci's advice doesn't work, can you tell us some more about your environment? Do you have opam installed? A global bs-platform? reason-cli? (None of these should be a problem, just trying to get an idea.)

**Comment by boyswan** [comment]
So I think I've figured it out, seems like a process didn't quit properly and was running in the background! I can replicate if I run npm start, then try npm start in another terminal whilst it's running. Thanks for your help, sorry for the slight false alarm!

**Comment by Schmavery** [comment]
Thanks for letting us know, @boyswan! Glad you got it sorted out. Feel free to open more issues if I can help with reprocessing in any way.
