### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by glennsl** [Schmavery/reprocessing#58]
In the spirit of Open Source, I implore you to consider adding an appropriate license to the project. As it is, the project must be considered proprietary and can't be used without first asking for your permission.

I'd recommend an MIT license. It's what reprocessing.js and most Reason projects use.
See https://help.github.com/articles/licensing-a-repository/ for more information.

**Comment by bsansouci** [comment]
Thanks, we didn't intend to limit the usage of this! Good call.

**Comment by Schmavery** [comment]
Done! Hope that helps 😄
