### ISSUE TITLE
Add ability to create and draw on images

### ISSUE THREAD

**Issue by bsansouci** [Schmavery/reprocessing#66]
It's not very difficult to run into performance issues when running reprocessing on mobile web on Android, and we'd like to ensure that Reprocessing isn't too often the bottleneck.
After talking to @jaredly and @Schmavery it seems like a powerful tool would be to allow saving draw calls onto a texture which could then be drawn in one shot (2 triangles). 

This would look like:
```reason
let init = (env) => {
  { background: Draw.createTexture() }
};

let render = (state, env) => {
  /* This function would check if state.background is "null" and call the function if yes, otherwise it'll do nothing. This allows the user to write code with the mindset that everything inside render is executed at all points in time. Also it is a very easy upgrade from the draw calls you'd do normally to this. */
  Draw.updateTextureIfNull(state.background, (env) => {
    /* The env would be automatically set such that all draw calls inside here would be drawing onto the   
       texture buffer passed to updateTextureIfNull. */
    Draw.drawRect(..., env);
  });
  Draw.drawTexture(state.background);
};
```

Another idea is based on the observation that 2D games generally have different and separate layers, such that most objects in one layer stays in that layer, even if it moves inside that layer.
We could image having a first class `layer` concept which would allow the user to create a layer, make draw calls that are associated with the layer and then draw the layer.
I'm not exactly sure what this would look like. It might be a very similar API but would be higher level than "textures".

**Comment by Schmavery** [comment]
"not very difficult to run into performance issues when running reprocessing on mobile web on Android" -- not denying it's possible but would be great to get some examples we can try to benchmark. While being able to bake some expensive draws into a texture is definitely a powerful and cool ability (and I can think of a couple of applications right away), I could imagine several demos that wouldn't benefit from it.

- Not sure what the difference between layer and texture are.
- If we default the texture to empty (or switch inside the drawTexture call) we don't need "updateTextureIfNull".
- **Is there a way we can merge this with the `Draw.image` api** by making it possible to render to a loaded texture + add an api for creating a blank image? That seems like it would be sick.

**Comment by bsansouci** [comment]
cc @jaredly. It's be super helpful to have flame graphs on your next game, it would really help us make more informed optimizations.

Yeah this optimization isn't covering everything for sure. This is more of a product-driven development approach haha.

- re `layer`, yeah I can't think of any way it'd be different from an `imageT`.
- the only reason I pointed at `updateTextureIfNull` is to have the optimizations be the default behavior that people get. Otherwise the user has to track a boolean like `isLoaded` for each texture they make, which seems like a small barrier for usage. Maybe we can actually just make `imageT` not be abstract, and it'd be like `{loaded: bool, imageData: imageDataT}` which would allow people to do the simple check `if (!state.background.loaded)`. That seems good
- Yeah for sure, let's just do that.

**Comment by Schmavery** [comment]
What does "loaded" refer to in this case? If I remember correctly, for an image, it's true if the image has been loaded to the gpu. In the case of a "layer" do you still mean that? or would an empty image be unloaded even if it was on the gpu as an empty image.  I probably need to look more into what's possible here and understand better how we could set an arbitrary image as a draw target

One complication I could see happening is that since image load happens async, needing to wait for the load to complete before drawing to the image. Here I could definitely see the benefit of exposing the "loaded" bool, though it would be even nicer for the system to somehow just "handle it".
IIRC, processing has some mechanism whereby the system waits between running setup and starting to call draw for all assets to load. I considered adding this at some point but had never found it necessary until now (maybe).

**Comment by jaredly** [comment]
I think for the first pass we should keep it simple:
- `Draw.createTexture: unit -> imageT`
- `Draw.withTexture: (imageT, envT -> unit) -> unit`
(and maybe)
- `Draw.isImageLoaded: (imageT) -> boolean`

We can do fancy things like waiting for stuff to load, or tracking whether you've drawn to the background, once we try the basic stuff out.

**Comment by Schmavery** [comment]
This is done apart from #76
