### ISSUE TITLE
Test createImage/withImage on Linux

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/reprocessing#76]
@bsansouci recently added the functionality mentioned in #66 😄, but we haven't tested it for Linux machines yet (just windows + mac). We should probably do this at some point to keep compatibility going across the board.

This change involves some slightly hacky updates to reasongl to make it load some frameBuffer-related functions that aren't in GL 2.1 (which is the api we use for the most part), so it's possible there will be some issues.

**Comment by Schmavery** [comment]
@bsansouci can you link to some example project that uses this functionality to make it easier for someone to test

**Comment by bsansouci** [comment]
Sorry I messed up, you need to return `image` from draw.
```reason
open Reprocessing;

let setup = (env) => {
  Env.size(~width=200, ~height=200, env);
  Draw.createImage(200, 200, env);
};

let draw = (image, env) => {
  Draw.background(Constants.black, env);
  if (!Draw.isImageDrawnTo(image)) {
    Draw.withImage(image, env, (env) => {
      Draw.fill(Constants.red, env); 
      Draw.rect(~pos=(50, 50), ~width=100, ~height=100, env)
    });
  };
  Draw.image(image, ~pos=(0, 0), env);
  image
};

run(~setup, ~draw, ());
```

**Comment by bsansouci** [comment]
Amazing, thanks for testing!
