### ISSUE TITLE
Antialiasing

### ISSUE THREAD

**Issue by Schmavery** [Schmavery/reprocessing#9]
We have anti-aliasing automatically on web, but not on native.  Can we fix this?  Probably something that should be fixed at the regl level.

**Comment by Schmavery** [comment]
Related to https://github.com/bsansouci/regl/issues/6

**Comment by Schmavery** [comment]
Whoever can hook this up successfully gets major internet points: https://github.com/mrdoob/three.js/blob/6c7f000734f8579da37fb39e5c2e9e5e2dfb14f8/examples/js/shaders/SMAAShader.js

**Comment by bsansouci** [comment]
antialiasing is disabled on web since https://github.com/bsansouci/regl/commit/ee89240844f298bdd221cb9a6bb81ca4c9fc3dcb but it'd be nice to have it back thanks to some crazy shader and off-screen rendering.

**Comment by Schmavery** [comment]
I'm working on being able to render to a hi dpi surface for now but it would probably still be nice to have this.

**Comment by Schmavery** [comment]
PRs to https://github.com/bsansouci/reasongl-native/pull/1 and https://github.com/bsansouci/reasongl-web/pull/2 are up to support AA in both web and native! 😄 @jaredly @bsansouci

**Comment by Schmavery** [comment]
These PRs are merged, we now have AA support.
