### ISSUE TITLE
Switch to a CLI instead of cloning the repo for reprocessing-example

### ISSUE THREAD

**Issue by mtoso** [Schmavery/reprocessing#90]
Hi, I was wondering if there is some interest on having a CLI to generate a base project scaffold instead of cloning the reprocessing-example repo.
Something like:
```
npx create-reprocessing-app my-app
```
If it sounds something useful I can work on it.

Thanks

**Comment by bsansouci** [comment]
Hey @mtoso, is there anything that the reprocessing-example repo lacked that you would like to see? 
Was there some ambiguity about how to get started?

We'd like to keep it simple for now! We would love some help with some missing feature though, like https://github.com/Schmavery/reprocessing/issues/83 or https://github.com/Schmavery/reprocessing/issues/47 :)

**Comment by Schmavery** [comment]
`alias create-reprocessing-app='git clone https://github.com/Schmavery/reprocessing.git'`?

**Comment by vkammerer** [comment]
+1 for keeping it simple and just cloning the repo

**Comment by mtoso** [comment]
Didn't want to create anything complicate but totally fine on keep it the way it is now. Thanks for the feedbacks.

**Comment by Schmavery** [comment]
Thanks for the suggestion though!
If there's anything we can simplify/improve about our instructions then we're always open to hearing it and we'd be really happy to add a link in our README to something cool you build using reprocessing :)

**Comment by mtoso** [comment]
Thanks @Schmavery. Hope that you guys don't mind but i built a generator for my self just to try. 
It is here https://github.com/mtoso/create-reprocessing-app
