### ISSUE TITLE
NoLoop equivalent?

### ISSUE THREAD

**Issue by seethroughtrees** [Schmavery/reprocessing#97]
I'm drawing from large data sets that require interpolation, and is not something i would need to recalculate in a loop.  I would prefer to manually call a redraw() function on events.

My question is:

I've seen [NoLoop](https://processing.org/examples/noloop.html) and redraw() documented in the Processing docs.  Is there an equivalent in Reprocessing?  Or a pattern I'm not finding?

I ideally want to be able to draw, and just manually control redraw.  Or am I missing a concept?

Thanks.

**Comment by bsansouci** [comment]
Hey @seethroughtrees good question! We'll discuss adding that with @Schmavery but in the meantime I think you can replicate this with a simple boolean in your state. 
I think we don't clear the buffer for you until you call `background`, if you do something to the effect of
```reason
open Reprocessing;
type stateT = { shouldRedraw: bool};

let setup = (env) => {
  Env.size(~width=200, ~height=200, env);
  {shouldRedraw: true}
};

let draw = ({shouldRedraw}, env) => {
  if(shouldRedraw) {
    Draw.background(Constants.black, env);
    Draw.fill(Constants.red, env); 
    Draw.rect(~pos=(50, 50), ~width=100, ~height=100, env) ;
  };
  if(Env.mousePressed(env)) {
    {shouldRedraw: true}
  } else {
    {shouldRedraw: false}
  }
};

run(~setup, ~draw, ());
```

**Comment by seethroughtrees** [comment]
Thanks @bsansouci , that example makes perfect sense!

**Comment by Schmavery** [comment]
Alternatively, create a draw function but don't pass it to `run` and instead just call it manually in setup and in any event listener you care about.

**Comment by seethroughtrees** [comment]
I had no problem with just removing the draw function and calling it manually.  Glad this will be here for anyone searching in the future.  Closing.

**Comment by seethroughtrees** [comment]
:) is there a separate discord room for reprocessing or graphics drawing in the reasonml channel?  seems it would be super helpful to have a central place for people to discuss viz needs and solutions.

**Comment by bsansouci** [comment]
@seethroughtrees Feel free to ping me on #bindings-to-libraries for now, or directly. You can also open a topic on reasonml.chat

**Comment by Schmavery** [comment]
eh this isn't really a binding to a library.. but yeah just tag ben or I (same usernames in discord) wherever in discord. If enough conversations come up maybe it'll make sense but for now there's probably not enough traffic idk

**Comment by seethroughtrees** [comment]
thanks @bsansouci and @Schmavery !   i definitely think a lot of good could come from focused discussions on graphics in reasonml.   i'll look into starting a channel if someone hasn't already done it :)
